configure.ac: fix gettimeofday() args detection
The configure check for gettimeofday() was failing not because of the
arguments, but because exit() was undeclared.

conftest.c: In function 'main':
conftest.c:177:20: error: implicit declaration of function 'exit' [-Werror=implicit-function-declaration]
  177 | struct timeval tv; exit(gettimeofday(&tv, NULL));
      | ^~~~
conftest.c:174:1: note: include '<stdlib.h>' or provide a declaration of 'exit'